-- MySQL Script generated by MySQL Workbench
-- Sat Oct  3 15:14:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `milestone` DEFAULT CHARACTER SET utf8 ;
USE `milestone` ;

-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milestone`.`USERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `FIRST_NAME` VARCHAR(45) NULL,
  `LAST_NAME` VARCHAR(45) NULL,
  `USERNAME` VARCHAR(45) NULL,
  `ROLE` INT NULL,
  `PASSWORD` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ADDRESSES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milestone`.`ADDRESSES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `ADDRESSTYPE` INT NULL,
  `ISDEFAULT` TINYINT NULL,
  `USERS_ID` INT NULL,
  `STREET` VARCHAR(45) NULL,
  `CITY` VARCHAR(45) NULL,
  `STATE` VARCHAR(45) NULL,
  `POSTALCODE` VARCHAR(45) NULL,
  `ADDRESSEScol` VARCHAR(45) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milestone`.`ORDERS` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `DATE` DATETIME NULL,
  `USERS_ID` INT NULL,
  `ADDRESS_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `USERS_ID_idx` (`USERS_ID` ASC),
  INDEX ` ADDRESS_ID_idx` (`ADDRESS_ID` ASC),
  CONSTRAINT `USERID`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `milestone`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT ` ADDRESSID`
    FOREIGN KEY (`ADDRESS_ID`)
    REFERENCES `milestone`.`ADDRESSES` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDERNOTES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milestone`.`ORDERNOTES` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOTES` VARCHAR(45) NULL,
  `DATE` DATETIME NULL,
  `ORDERS_ID` INT NULL,
  `USERS_ID` INT NULL,
  PRIMARY KEY (`ID`),
  INDEX `USERS_ID_idx` (`USERS_ID` ASC),
  INDEX `ORDERS_ID_idx` (`ORDERS_ID` ASC),
  CONSTRAINT `USERSID`
    FOREIGN KEY (`USERS_ID`)
    REFERENCES `milestone`.`USERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `ORDERSID`
    FOREIGN KEY (`ORDERS_ID`)
    REFERENCES `milestone`.`ORDERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUCTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milestone`.`PRODUCTS` (
  `ID` INT NOT NULL,
  `PRODUCTNAME` VARCHAR(45) NULL,
  `DESCRIPTION` TEXT(200) NULL,
  `PRICE` FLOAT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ORDERDETAILS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `milestone`.`ORDERDETAILS` (
  `ID` INT NOT NULL,
  `ORDERS_ID` INT NULL,
  `PRODUCTS_ID` INT NULL,
  `QUANTITY` INT NULL,
  `CURRENTPRICE` FLOAT NULL,
  `CURRENTDESCRIPTION` TEXT(200) NULL,
  PRIMARY KEY (`ID`),
  INDEX `ORDERS_ID_idx` (`ORDERS_ID` ASC),
  INDEX `PRODUCT_ID_idx` (`PRODUCTS_ID` ASC),
  CONSTRAINT `ORDERS_ID`
    FOREIGN KEY (`ORDERS_ID`)
    REFERENCES `milestone`.`ORDERS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `PRODUCT_ID`
    FOREIGN KEY (`PRODUCTS_ID`)
    REFERENCES `milestone`.`PRODUCTS` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
